site_name: "Alisa Chikomazova | Portfolio"
site_url: https://alice-chiko.github.io/

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - python
  locale: en

extra_css:
  - extra.css

docs_dir: 'src/docs'

nav:
  - Welcome: index.md
  - About me: author.md
  - Projects:
      - Overview: labs.md
      - Typing Practice: laboratory_works/train.md
      - Term 1:
          - Lab 1: laboratory_works/term_1/labs/lab_1.md
          - Lab 2: laboratory_works/term_1/labs/lab_2.md
          - Lab 3: laboratory_works/term_1/labs/lab_3.md
          - Lab 4: laboratory_works/term_1/labs/lab_4.md
          - Lab 5: laboratory_works/term_1/labs/lab_5.md
          - Lab 6: laboratory_works/term_1/labs/lab_6.md
          - Lab 7: laboratory_works/term_1/labs/lab_7.md
          - Lab 8: laboratory_works/term_1/labs/lab_8.md
          - Lab 9: laboratory_works/term_1/labs/lab_9.md
          - Lab 10: laboratory_works/term_1/labs/lab_10.md
          - Lab 11: laboratory_works/term_1/labs/lab_11.md
      - Term 2:
          - Lab 1: laboratory_works/term_2/labs/lab_1.md
          - Lab 2: laboratory_works/term_2/labs/lab_2.md
          - Lab 3: laboratory_works/term_2/labs/lab_3.md
          - Lab 4: laboratory_works/term_2/labs/lab_4.md
          - Lab 5: laboratory_works/term_2/labs/lab_5.md
          - Lab 6: laboratory_works/term_2/labs/lab_6.md
          - Lab 7: laboratory_works/term_2/labs/lab_7.md
          - Lab 8: laboratory_works/term_2/labs/lab_8.md
          - Lab 9: laboratory_works/term_2/labs/lab_9.md
          - Lab 10: laboratory_works/term_2/labs/lab_10.md